apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  primary.cnf: |
    # Configuración del primario
    [mysqld]
    log-bin
  replica.cnf: |
    # Configuración de los secundarios
    [mysqld]
    super-read-only
