apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "dbTest"
        - name: MYSQL_USER
          value: "user"
      ports:
        - containerPort: 3306
          name: mysql
